timeout: 0

/BoringOS M36 graphical terminal
    protocol: limine
    path: boot():/boot/kernel.elf
    resolution: 800x600x32
    module_path: boot():/boot/user/boring-display.elf
    module_string: boringos-boring-display
    module_path: boot():/boot/user/boringwm.elf
    module_string: boringos-boringwm
