timeout: 0

/BoringOS native BoringWM
    protocol: limine
    path: boot():/boot/kernel.elf
    resolution: 800x600x32
    module_path: boot():/boot/user/boring-display.elf
    module_string: boringos-boring-display
    module_path: boot():/boot/user/boringwm.elf
    module_string: boringos-boringwm
    module_path: boot():/boot/user/wm-client-a.elf
    module_string: boringos-wm-client-a
    module_path: boot():/boot/user/wm-client-b.elf
    module_string: boringos-wm-client-b
    module_path: boot():/boot/user/wm-client-c.elf
    module_string: boringos-wm-client-c
