timeout: 0

/BoringOS M37 native desktop session startup
    protocol: limine
    path: boot():/boot/kernel.elf
    resolution: 800x600x32
    module_path: boot():/boot/user/boring-init.elf
    module_string: boringos-boring-init
