timeout: 0

/BoringOS
    protocol: limine
    path: boot():/boot/kernel.elf
    resolution: 1024x768x32
    module_path: boot():/boot/user/boring-init.elf
    module_string: boringos-boring-init
    module_path: boot():/boot/user/boring-shell.elf
    module_string: boringos-boring-shell
