timeout: 5
mouse: no

/BoringOS M61 bootable persistent USB root
    protocol: limine
    path: boot():/boot/kernel.elf
    resolution: 800x600x32
    module_path: boot():/boot/user/boring-init.elf
    module_string: boringos-boring-init
