timeout: 0

/BoringOS
    protocol: limine
    path: boot():/boot/kernel.elf
    module_path: boot():/boot/user/boring-display.elf
    module_string: boringos-boring-display
    module_path: boot():/boot/user/display-client-a.elf
    module_string: boringos-display-client-a
    module_path: boot():/boot/user/display-client-b.elf
    module_string: boringos-display-client-b
