timeout: 5
mouse: no

/BoringOS M68 safe higher GOP 1920x1080
    protocol: limine
    path: boot():/boot/kernel.elf
    resolution: 1920x1080x32
    module_path: boot():/boot/user/boring-init.elf
    module_string: boringos-boring-init

/BoringOS M68 known-safe 800x600 fallback
    protocol: limine
    path: boot():/boot/kernel.elf
    resolution: 800x600x32
    module_path: boot():/boot/user/boring-init.elf
    module_string: boringos-boring-init
