#ifndef BORING_M61_RUNTIME_HID_H
#define BORING_M61_RUNTIME_HID_H

#include <stdbool.h>
#include <stdint.h>

#if defined(BORING_M61_PHYSICAL_BREADCRUMBS)
enum m61_post37_control_flow_code {
    M61_POST37_ARM_RETURNED = 0x20,
    M61_POST37_FRAMEBUFFER_PRESENT_RETURNED = 0x21,
    M61_POST37_DISPLAY_PRESENT_RETURNED = 0x22,
    M61_POST37_DISPLAY_EVENT_LOOP_REENTRY = 0x23,
    M61_POST37_EVENT_SYSCALL_ENTRY = 0x24,
    M61_POST37_INPUT_OWNER_TRUE = 0x25,
    M61_POST37_FAST_READY = 0x26,
    M61_POST37_READY_IPC_LISTENER = 0x27,
    M61_POST37_READY_IPC_ENDPOINT = 0x28,
    M61_POST37_READY_INPUT = 0x29,
    M61_POST37_READY_FD = 0x2a,
    M61_POST37_READY_IPC_HUP = 0x2b,
    M61_POST37_POLL_ERROR = 0x2c,
    M61_POST37_INPUT_OWNER_FALSE = 0x2d
};

enum m61_runtime_hid_post_code {
    M61_RUNTIME_HID_POST_A_SERVICE_LOOP = 0xc9,
    M61_RUNTIME_HID_POST_B_TRANSFER_EVENT = 0xca,
    M61_RUNTIME_HID_POST_C_EVENT_VALIDATED = 0xcb,
    M61_RUNTIME_HID_POST_D_INPUT_QUEUED = 0xcc,
    M61_RUNTIME_HID_POST_E_INPUT_READ = 0xcd
};

enum m61_runtime_xhci_observation_code {
    M61_RUNTIME_XHCI_POST_HID_ENDPOINTS_ARMED = 0x5e,
    M61_RUNTIME_XHCI_POST_ANY_CYCLE_READY_EVENT = 0x5f,
    M61_RUNTIME_XHCI_POST_PORT_STATUS_AT_HEAD = 0xce,
    M61_RUNTIME_XHCI_POST_OTHER_EVENT_AT_HEAD = 0xcf
};

enum m66_physical_usb_mouse_post_code {
    M66_POST_CONFIGURATION_VALID = 0x80,
    M66_POST_BOOT_MOUSE_FOUND = 0x81,
    M66_POST_GENERIC_MOUSE_CANDIDATE = 0x82,
    M66_POST_HID_DESCRIPTOR_ACCEPTED = 0x83,
    M66_POST_REPORT_DESCRIPTOR_REQUESTED = 0x84,
    M66_POST_REPORT_DESCRIPTOR_RECEIVED = 0x85,
    M66_POST_REPORT_DESCRIPTOR_PARSED = 0x86,
    M66_POST_MOUSE_LAYOUT_SELECTED = 0x87,
    M66_POST_ALL_XHCI_READY = 0xd0,
    M66_POST_HUB_DETECTED = 0xd1,
    M66_POST_HUB_DESCRIPTOR_ACCEPTED = 0xd2,
    M66_POST_DOWNSTREAM_CONNECTED = 0xd3,
    M66_POST_DOWNSTREAM_RESET = 0xd4,
    M66_POST_DOWNSTREAM_ADDRESSED = 0xd5,
    M66_POST_DOWNSTREAM_DESCRIPTORS = 0xd6,
    M66_POST_DOWNSTREAM_HID_SUPPORTED = 0xd7,
    M66_POST_DOWNSTREAM_HID_UNSUPPORTED = 0xd8,
    M66_POST_DOWNSTREAM_INTERRUPT_ARMED = 0xd9,
    M66_POST_DOWNSTREAM_MOUSE_REPORT = 0xda,
    M66_POST_CANONICAL_MOUSE_MOVE = 0xdb,
    M66_POST_RESET_SET_ENTER = 0xdc,
    M66_POST_RESET_SET_COMPLETE = 0xdd,
    M66_POST_RESET_FIRST_STATUS_COMPLETE = 0xde,
    M66_POST_RESET_FIRST_STATUS_RAW = 0xdf,
    M66_POST_RESET_STILL_ACTIVE = 0xe0,
    M66_POST_RESET_COMPLETE_DISABLED = 0xe1,
    M66_POST_RESET_COMPLETE_ENABLED = 0xe2,
    M66_POST_RESET_SPEED_VALID = 0xe3
};

void boring_m61_runtime_hid_arm(void);
bool boring_m61_runtime_hid_is_armed(void);
void boring_m61_post37_witness(uint8_t code);
void boring_m61_runtime_hid_post(uint8_t code);
void boring_m61_runtime_xhci_observe(uint8_t code);
void boring_m66_physical_usb_mouse_witness(uint8_t code);
#endif

#endif
